apiVersion: v1
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: billpay-deployment
    version: staging
  name: billpay-deployment
  namespace: gwiza-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billpay-service
      version: staging
  template:
    metadata:
      labels:
        app: billpay-service
        version: staging
    spec:
      imagePullSecrets:
      - name: docker-keys
      containers:
      - image: brugambwa/gv3_ms_billpayment:1
        name: billpay-service
        ports:
        - containerPort: 7773
        env:
          - name: DEV_DB_USER
            valueFrom:
              secretKeyRef:
                name: gwiza-staging-secret
                key: DEV_DB_USER
          - name: DEV_DB_PASS
            valueFrom: 
              secretKeyRef:
                name: gwiza-staging-secret
                key: DEV_DB_PASS
          - name: DEV_DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: gwiza-staging-config
                key: DEV_DB_HOST  


# Service Definition
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: billpay-service
  name: billpay-service
  namespace: gwiza-staging
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 7773
      protocol: TCP
  selector:
    app: billpay-service
  type: ClusterIP

# Ingress Definition