apiVersion: v1
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: billpay-deployment
    version: staging
  name: billpay-deployment
  namespace: gwiza-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billpay-service
      version: staging
  template:
    metadata:
      labels:
        app: billpay-service
        version: staging
    spec:
      containers:
        - image: brugambwa/gv3_ms_billpayment:1
          name: billpay-service
          ports:
          - containerPort: 7773
        imagePullSecrets:
        - name: registry-secret
          envFrom:
              - configMapRef:
                  name: gwiza-staging-config 
              - secretRef:
                  name: gwiza-staging-secret

# Service Definition
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: billpay-service
  name: billpay-service
  namespace: gwiza-staging
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 7773
      protocol: TCP
  selector:
    app: billpay-service
  type: ClusterIP

# Ingress Definition
